### ISSUE TITLE
Add a 'Knuckles in Sonic 2' branch

### ISSUE THREAD

**Issue by Clownacy** [sonicretro/s2disasm#14]
I'd like to get around to this sometime. I think I've already got most of the work out of the way, since KiS2 was based on REV02, which had those massive linker data differences that took forever to add.

On paper, all I should have to do is ORG the 68k code to the right location, strip out the sound driver and art/level files, add Knuckles, and then I can get to the good part of finding whatever neat little changes KiS2 contains.

**Comment by MainMemory** [comment]
Using the ORG directive in AS causes the ROM to be padded to the specified address, you'd want to use PHASE instead. Also, what about the existing KiS2 disassembly repo?

**Comment by Clownacy** [comment]
Whoops. Yeah, that.

I suppose the old KiS2 disasm will just become useless. I'd rather do what I said above than try to bring a whole disasm up to date with S2 Git.

**Comment by MainMemory** [comment]
I guess it makes some amount of sense to make a KiS2 based off the S2 disasm, assuming everything lines up.

**Comment by Clownacy** [comment]
https://github.com/sonicretro/s2disasm/tree/knuckles-in-sonic-2

Finally...
