### ISSUE TITLE
REV02 might be wrong

### ISSUE THREAD

**Issue by Clownacy** [sonicretro/s2disasm#21]
So, I realised there's a chance Sonic Jam's port of Sonic 2 is based on REV02, so I took a look. Long story short, yes, but it's missing a few things. Namely all the mistakes.

It contains all of the bugfixes that we have for REV02, but it's missing the bugs it supposedly introduced like the broken mirroring on Silver Sonic/Grabber's sprites, not being able to spin dash off the Tornado anymore, and the WFZ conveyor belt letting you walk on air. It's also missing the pointless adjustments to HPZ/OOZ's animated art tables.

Note that all of these bugs were introduced by strange issues with what were probably constants in the original source code. For example, here's the code that causes the sprite mirroring bug:
```
    if gameRevision<2
	andi.b	#$FC,d0
	move.b	status(a0),d2
	andi.b	#$FC,d2
	move.b	render_flags(a1),d1
	andi.b	#3,d1
    else
	; Peculiarly, REV02 changes this to only inherit the Y-flip.
	; This causes a bug where some sprites are displayed backwards (Silver Sonic's sparks and Grabber's legs).
	andi.b	#$FD,d0
	move.b	status(a0),d2
	andi.b	#$FD,d2
	move.b	render_flags(a1),d1
	andi.b	#2,d1
    endif
```
Here's the one for the Tornado:
```
    if gameRevision<2
	andi.b	#p1_standing,d0	; 'on object' bit
	andi.b	#p1_standing,d1	; 'on object' bit
    else
	; 'fixes' the player being able to spin dash off the Tornado
	andi.b	#1,d0	; 'X-flipped' bit???
	andi.b	#1,d1	; 'X-flipped' bit???
    endif
```
And here's the WFZ platform one:
```
    if gameRevision<2
	andi.b	#standing_mask,d0
    else
	; I don't know what this change was meant to do, but it causes
	; Sonic to not fall off ObjBD's ascending platforms when they retract,
	; making him hover.
	andi.b	#2,d0	; 'Y-flipped' bit???
    endif
```
Admittedly, there's a chance the devs just fixed these things, but I'm more convinced Sonic Compilation/Classics _introduced_ these issues. Knuckles in Sonic 2 doesn't have any of these issues either, and that was also based on REV02, but came out _before_ Compilation.

So now I'm considering splitting REV02 into a "real" REV02 build, and a Sonic Compilation build, with those [extra changes that I removed](https://github.com/sonicretro/s2disasm/commit/da9bfb94edc7ccb2f9f78e78512ea126b49e1c8d).

**Comment by Clownacy** [comment]
Alright, REV02 is _definitely_ wrong. The problem with KiS2 and Sonic Compilation is that neither of them have REV02's original header.

[The Mega Play version](http://info.sonicretro.org/Sonic_the_Hedgehog_2_(arcade_game)) does.

And yes, it lacks Compilation's bugs. The title screen was updated, changing the copyright year to 1993, putting this build a year before KiS2, two years before Compilation, and four years before Sonic Jam.

```
SEGA GENESIS    
(C)SEGA 1992.SEP
SONIC THE       
      HEDGEHOG 2
                
SONIC THE       
      HEDGEHOG 2
                
GM 00001051-02Œ>
J               
......ÿÿ.ÿ...ÿÿÿ
                
                
                
                




JUE             
```
You have no clue how long I've wanted to see this :l

Thanks to this ROM, I now know that REV02 didn't remove the `nop`s in ErrorTrap. That was just another change Compilation made.

**Comment by flamewing** [comment]
Nice finds. Eagerly awaiting the "true" rev02 commits!

**Comment by Clownacy** [comment]
I've pushed my disassembly to the megaplay branch. Unfortunately, there's one discrepency: while the Compilation bugs aren't there, the edited HPZ/OOZ animated art tables are. I'll have to double-check if they really are absent from KiS2, and what they do in the first place.

**Comment by Clownacy** [comment]
Welp, I'm dumb. KiS2 has the animated-level-art edits as well. Also, I figured out what the changes are for:
```
; In REV02, for some reason these blank tiles' palette line was changed to lines 3 and 4.
; This is consistent with MTZ's blank tiles.
; Notably, the new palette lines' first entry always happens to match the current VDP background colour.
```

**Comment by Clownacy** [comment]
So now the Compilation bugs have been stripped from the main branch. Unfortunately, we'll probably never have a real bit-perfect REV02 ROM, since the JmpTos are massively different, even between Sonic Classics and S2 Mega Play. Still, this should be _functionally_ perfect now, at least.
