### ISSUE TITLE
Portable way of checking bit-perfection

### ISSUE THREAD

**Issue by Clownacy** [sonicretro/s2disasm#24]
Just leaving this here before I forget: I think it's nice that this disasm is portable, but right now checking bit-perfection isn't. Granted, it's something you can do yourself with a hex editor or any assortment of standard Linux utilities, but still, it's a feature that the disasm only provides for Windows users.

I'm wondering if it's worth making a quick hash-verifying tool. Write it in C/C++, and it can be compiled at run-time just like the other tools, so portability's a non-issue.

A hash checker would remove the need for those pre-built ROMs cluttering the main directory, but it wouldn't give the same feedback as the current chkbitperfect, which shows you each differing byte. On the other hand, in the event the ROM is _very_ different, this quickly becomes a downside since it winds up spamming the console for a good minute or two.

A hash-checker can work more like [s1disasm's build.py](https://github.com/sonicretro/s1disasm/blob/AS/build_defs.py), comparing the ROM against hashes of each revision and telling you which one it matches, instead of the current system of having one script for each revision, and expecting the user to select the right one.

Thoughts?

**Comment by MainMemory** [comment]
yes

**Comment by flamewing** [comment]
I would suggest doing 2 or 3 different hashes to guard against hash collisions.

Another approach is to move the ROMs to a different direction, merge chkbitperfect into the build script, and have the build script select which ROM to compare against based on the revision being built.

**Comment by Clownacy** [comment]
Hash collisions? I was thinking SHA-256, not a plain checksum.

Also how would the build script know what revision the user is trying to build?

**Comment by MainMemory** [comment]
Either by having a separate script for each revision, or by exporting the revision constant from AS.
