### ISSUE TITLE
Broken rings effect on the Special Stage.

### ISSUE THREAD

**Issue by Storm3000** [sonicretro/s2disasm#26]
Hi, Iory90.

I'm using the Sonic 2 Improvement hack v5.1 (it's a fantastic hack, by the way). But it seems there's a bug. When entering into the first Special Stage using Sonic and Tails, or Tails only, the stars effect when you collect rings looks broken. This doesn't happen in the original Sonic 2 Rev A.

**Comment by MainMemory** [comment]
This isn't the issue tracker for the Sonic 2 Improvement hack, this is the issue tracker for the Sonic 2 disassembly. If the problem doesn't exist in the original game, then it's not relevant to this project.
