### ISSUE TITLE
How do you open/preview the art file?

### ISSUE THREAD

**Issue by kirkas** [sonicretro/s2disasm#28]
Probably a noob question, but what software to you use to open and display art? Say if I want to see what [this](https://github.com/sonicretro/s2disasm/blob/master/art/uncompressed/Background%20clouds%20(HTZ).bin) looks like?

**Comment by MainMemory** [comment]
Personally, I use [YY-CHR.NET](http://www.romhacking.net/utilities/958/) (set format to 4BPP MSX) and [the FW-KENSC Shell Extension](http://forums.sonicretro.org/index.php?showtopic=36252) for compressed files.

**Comment by kirkas** [comment]
Thank you!
