### ISSUE TITLE
clearRAM negative size results in invalid behaviour

### ISSUE THREAD

**Issue by NatsumiFox** [sonicretro/s2disasm#30]
clearRAM does not check if the end address is actually less than the start address, which can cause negative offsets which end up causing strange issues. This can be a problem for people who wish to rearrange RAM and get unintended strange effects after that. It requires some knowledge and luck to find these kind of issues correctly, as the code is abstracted behind a macro. Should the macro cause an error when the length is negative?

**Comment by flamewing** [comment]
Fixed in 3143b40c.
