### ISSUE TITLE
Knuckles in Sonic 2: Casino Night Zone object layouts

### ISSUE THREAD

**Issue by Brainulator9** [sonicretro/s2disasm#46]
Exclusively in the Knuckles in Sonic 2 branch, the file containing the compressed graphics for the title screen's "THE ECHIDNA IN" text also include object layout data for both acts of Casino Night Zone. This is actually referenced by the KiS2 object layout jump table located at $DF370 in the Sonic & Knuckles ROM: $33F06E contains Act 1's data while $33F74C contains Act 2's data.

**Comment by Clownacy** [comment]
Thanks for finding that out. I really ought to make a tool to detect how many bytes in a compressed file are actually read by the decompressor, which would help with finding things like this.
