### ISSUE TITLE
I am trying to restore Wood Zone in a similar manner to Clownacy restoring Hidden Palace Zone and I'm attempting to add an extra slot for Wood Zone's background. How do I add to the Off_Level table? You're cool ;)

### ISSUE THREAD

**Issue by NickArcadeNerd** [sonicretro/s2disasm#51]
Warning: Table Off_Level has 18 entries, but it should have 17 entries
> > > s2.asm(90184) zoneOffsetTableEntry(1) zoneTableEntry(6):22: error #1820: expression must be evaluatable in first pass
> > > zone_table_addr+zone_id_{cur_zone_str}*zone_entry_len*zone_entries
> > >                 !org zone_table_addr+zone_id_{cur_zone_str}*zone_entry_len*zone_entries
> > >                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Brainulator9** [comment]
Replace the line
`	zoneOffsetTableEntry.w Level_EHZ1	; 4`
with
`	zoneOffsetTableEntry.w Level_WZ1	; 4`

That takes care of the offset table, but you'll need to ensure that Level_WZ1 (I used that name as a placeholder) actually exists.
