### ISSUE TITLE
Broken bugfixes in OptionScreen_Select_Not1P and UpdateWaterSurface

### ISSUE THREAD

**Issue by OrionNavattan** [sonicretro/s2disasm#53]
The bugfix in OptionScreen_Select_Not1P is a bit broken. It’s setting the emerald variables to 1 rather than clearing them due to a missing `moveq #0,d0` instruction. 
```
OptionScreen_Select_Not1P:
	subq.b	#1,d0
	bne.s	OptionScreen_Select_Other
	; Start a 2P VS game
	moveq	#1,d0
	move.w	d0,(Two_player_mode).w
	move.w	d0,(Two_player_mode_copy).w
    if fixBugs
	; There should be a ‘moveq #0,d0’ here!
	move.w	d0,(Got_Emerald).w
	move.l	d0,(Got_Emeralds_array).w
	move.l	d0,(Got_Emeralds_array+4).w
    endif

**Comment by Clownacy** [comment]
Oh wow, whoops. Thanks for catching that.

**Comment by OrionNavattan** [comment]
Found a second broken bugfix, this time in UpdateWaterSurface. The way it checks for the game pausing is incomplete; while either player can pause the game, the fix only checks player 1's input, so the bug will still occur if player 2 initiates the pause. Thankfully, there is code elsewhere in the game that works to fix this.

```
   if fixBugs
        ; Code from PauseGame (and other places) that checks input of both players.
	move.b	(Ctrl_1_Press).w,d0 ; is Start button pressed?
	or.b	(Ctrl_2_Press).w,d0 ; (either player)
	andi.b	#button_start_mask,d0
	bne.s	+   ; branch if so
    endif
```

**Comment by Clownacy** [comment]
I blame that one on the vanilla game: Object 4 contains that same bug twice. Thanks for pointing it out: the more fixes, the merrier.
