### ISSUE TITLE
Knuckles in Sonic 2 Broken Jump Sprite when fixBugs is Enabled

### ISSUE THREAD

**Issue by PeytonRG** [sonicretro/s2disasm#54]
![image](https://github.com/sonicretro/s2disasm/assets/29259224/2c7acc43-a3e5-45fe-886a-947de0757ad4)
Hello, I have been toying around with the KiS2 disassembly and making changes to the code, and I have found an issue related to the fixBugs flag. 

When jumping, Knuckles' sprite breaks down the middle, and the right side becomes garbled. I have observed this on original hardware via Mega Everdrive Pro, on clownmdemu, and on lr-genesis-plus-gx. I also have standalone KiS2 enabled for emulator compatibility. Not sure if that's also a cause.

### To reproduce, set the following flags
1. fixBugs = 1
1. standaloneKiS2 = 1 (again, this one might not be necessary, but it was how I built it)

### Note:
This only appears to happen when fixBugs = 1. Turning it off resolves this issue at the expense of whatever fixes are relevant to KiS2.

**Comment by Clownacy** [comment]
Thanks for pointing that out. That's [the DMA boundary bug](https://sonicresearch.org/community/index.php?threads/hardware-emulator-quirks.4147/#post-81411), which is an issue with the Mega Drive hardware itself. The Sonic & Knuckles disassembly had to deal with this problem too, so I've backported its solution (in 80d82e65a5ec0d21c8ebd63cb2298d0bd941724d) to prevent it from happening.
