### ISSUE TITLE
Some labels are *way* too verbose

### ISSUE THREAD

**Issue by DevsArchive** [sonicretro/s2disasm#55]
Take for example this:

	DrawInitialBG_LoadWholeBackground_512x256:
		moveq	#0,d4	; Absolute plane Y coordinate.
	
		moveq	#256/16-1,d6 ; Height of plane in blocks minus 1.
	-	movem.l	d4-d6,-(sp)
		moveq	#0,d5
		move.w	d4,d1
		; This is just a fancy efficient way of doing 'if true then call this, else call that'.
		pea	+(pc)
		tst.w	(Two_player_mode).w
		beq.w	CalculateVRAMAddressOfBlockForPlayer1.AbsoluteXAbsoluteY
		bra.w	CalculateVRAMAddressOfBlockForPlayer1.AbsoluteXAbsoluteY_DoubleResolution
	+
		move.w	d1,d4
		moveq	#0,d5
		moveq	#512/16-1,d6 ; Width of plane in blocks minus 1.
		move	#$2700,sr
		bsr.w	DrawBlockRow.AbsoluteXAbsoluteYCustomWidth
		move	#$2300,sr
		movem.l	(sp)+,d4-d6
		addi.w	#16,d4
		dbf	d6,-
	
		rts

This is just downright ridiculous, especially when you are referencing other local labels, like "CalculateVRAMAddressOfBlockForPlayer1.AbsoluteXAbsoluteY_DoubleResolution". Personally, I'd shorten it down to "CalcBlockVRAM.AbsXY2P" or something of that sort.

**Comment by Clownacy** [comment]
What's the harm? This isn't the 90s or whenever when text editors could only display up to 80 characters per line.

'CalcBlockVRAM.AbsXY2P' conveys less information, making it less clear what the function does:
- 'Calculate block VRAM' could mean turning the block into data suitable for uploading to VRAM for all I know.
- It fails to specify that it is specifically for player 1. What would `CalculateVRAMAddressOfBlockForPlayer2` be called? CalcBlockVRAM2? CalcBlockVRAMP2? If you're going to specify which player one function is intended for, you might as well specify it for the other too.
- There's nothing 2-player-specific about the double-resolution code. Naming it in such a way is misleading.

Addressing all of these problems results in CalcBlockVRAMAddrP1.AbsXYDblRes, which is an incoherent string of gibberish, and expanding it into readable English results in CalculateBlockVRAMAddressPlayer1.AbsoluteXYDoubleResolution, so we've made barely any progress.
