### ISSUE TITLE
Timer_frames should be renamed

### ISSUE THREAD

**Issue by RealMalachi** [sonicretro/s2disasm#57]
Basically, Timer_frame and Timer_frames are way too similar in name. 
So the readers have easier access to context, Timer_frame is used for the HUD to count the time in-between seconds, and Timer_frames is a frame timer, like what most NES games use for framerules. Both of them are technically frame timers, but Timer_frame is a byte that ends at 60 and Timer_frames an unsigned word (or "short") that overflows back to 0.
Oh, and Timer_frame is never used for anything aside for the timer, while Timer_frames is. One typo can change that. This wasn't really an issue with Timer_centisecond, though that name was just generally inaccurate

Here are a few name suggestions I have:
Frame_timer, Framerule_timer, Level_frame_counter, Runtime_counter

**Comment by lilggamegenius** [comment]
We could probably shorten it to `Level_framecount` so it matches `Vint_runcount` but expresses the intent that this is only for the current level
