### ISSUE TITLE
knuckles in sonic 2 black screen error 

### ISSUE THREAD

**Issue by Lilredjuice** [sonicretro/s2disasm#60]
Im a linux user, and i tried building knuckles in sonic 2
i downloaded the zip file and used 'wine cmd' to use build.bat and thats when i got this conformation it says rom is about 40000 bytes (256kb) about 2f2 bytes are padding.  and when i tried the rom i see a black screen
![Screenshot from 2024-06-02 16-35-42](https://github.com/sonicretro/s2disasm/assets/134834835/3b0c2e4a-2fef-4d76-b874-b61514f77b70)
yeah so can anyone tell me what the HELL is going on??
thanks.

**Comment by Lilredjuice** [comment]
btw i tried lockon and its still a black screen

**Comment by Clownacy** [comment]
You need to lock-on with Sonic 2 and Sonic & Knuckles. If I remember correctly, the lock-on order is Sonic & Knuckles first, then Sonic 2, then Knuckles in Sonic 2.

You don't need to use Wine to build this: `build.lua` works natively on Linux.

**Comment by Lilredjuice** [comment]
....uhh what??

**Comment by Clownacy** [comment]
You execute it like a shell script. Just make sure you have your distro's Lua package installed.

**Comment by Lilredjuice** [comment]
okay  so blastem doesnt not support sonic 2 lock ons. Is there any other emulator that supports it??

**Comment by Clownacy** [comment]
Yes, though I'm sure that BlastEm supports it too. How are you locking-on the ROMs?

**Comment by Lilredjuice** [comment]
hmm lets start, i booted up sonic and knuckles first, then i press 'Lock-on', and then i use the sonic 2 rom and yeah it shows a black screen, they said it theirselves
![Screenshot from 2024-06-03 19-00-23](https://github.com/sonicretro/s2disasm/assets/134834835/db342d58-a305-4ba0-a78e-fcf9b18b9325)

**Comment by Clownacy** [comment]
Oooooh, that. What I was referring to was making your own locked-on ROM yourself. You literally just make a single file that starts with _Sonic & Knuckles_'s ROM followed by _Sonic 2_'s ROM followed by the _Knuckles in Sonic 2_ ROM. A one-liner to do that using the terminal is this:

```
 cat sk.bin s2.bin kis2.bin > combined.bin
```
If doing all that is too much of a pain, you can set the `standaloneKiS2` variable at the start of `s2.asm` to `1`, which will make the disassembly produce a standalone ROM instead of a lock-on ROM.

**Comment by Lilredjuice** [comment]
ohhhhhh i get it

**Comment by Lilredjuice** [comment]
it worked,thanks so much clowancy!

**Comment by Clownacy** [comment]
Glad I could help!

**Comment by Lilredjuice** [comment]
so it turns out i made the kis2 UPMEM rom
